# Documentation
-    Quick Start Tutorial http://scikit-learn.org/stable/tutorial/basic/tutorial.html
-    scikit-learn Tutorials http://scikit-learn.org/stable/tutorial/index.html
-    User Guide http://scikit-learn.org/stable/user_guide.html
-    Example Gallery http://scikit-learn.org/stable/auto_examples/index.html

# Papers
If you interested in more information about how the project started and it’s vision, there are some papers you may want to check-out.
-    Scikit-learn: Machine Learning in Python (2011)
-    API design for machine learning software: experiences from the scikit-learn project (2013)

# Books
If you are looking for a good book, I recommend “Building Machine Learning Systems with Python”. It’s well written and the examples are interesting.

-    Learning scikit-learn: Machine Learning in Python (2013)
-    Building Machine Learning Systems with Python (2013)
-    Statistics, Data Mining, and Machine Learning in Astronomy: A Practical Python Guide for the Analysis of Survey Data (2014)

https://github.com/scikit-learn

Statistical inference is the process of using data analysis to deduce properties of an underlying probability distribution.[1] Inferential statistical analysis infers properties of a population, for example by testing hypotheses and deriving estimates. It is assumed that the observed data set is sampled from a larger population. Inferential statistics can be contrasted with descriptive statistics. Descriptive statistics is solely concerned with properties of the observed data, and it does not rest on the assumption that the data come from a larger population.
https://en.wikipedia.org/wiki/Statistical_inference


In [3]:
# help(sklearn)


In [4]:
from sklearn import datasets
iris=datasets.load_iris()
digits=datasets.load_digits()

In [6]:
dir(iris)

['DESCR', 'data', 'feature_names', 'target', 'target_names']

In [20]:
print(type(iris.data),'\n')
print(dir(iris.data))
iris.data.shape

<class 'numpy.ndarray'> 

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlsh

(150, 4)

In [21]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [36]:
print(type(digits.data),'\n')
print(dir(digits.data))
digits.data.shape

<class 'numpy.ndarray'> 

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlsh

(1797, 64)

In [37]:
print(digits.data,'\n')
print(digits.data.shape)

[[  0.   0.   5. ...,   0.   0.   0.]
 [  0.   0.   0. ...,  10.   0.   0.]
 [  0.   0.   0. ...,  16.   9.   0.]
 ..., 
 [  0.   0.   1. ...,   6.   0.   0.]
 [  0.   0.   2. ...,  12.   0.   0.]
 [  0.   0.  10. ...,  12.   1.   0.]] 

(1797, 64)


In [25]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [43]:
print(type(digits.images),'\n')
print(digits.images.shape)

<class 'numpy.ndarray'> 

(1797, 8, 8)


In [52]:
print(digits.data[0],'\n')
print(digits.data[0].reshape(-1,8))

digits.images[0]

[  0.   0.   5.  13.   9.   1.   0.   0.   0.   0.  13.  15.  10.  15.   5.
   0.   0.   3.  15.   2.   0.  11.   8.   0.   0.   4.  12.   0.   0.   8.
   8.   0.   0.   5.   8.   0.   0.   9.   8.   0.   0.   4.  11.   0.   1.
  12.   7.   0.   0.   2.  14.   5.  10.  12.   0.   0.   0.   0.   6.  13.
  10.   0.   0.   0.] 

[[  0.   0.   5.  13.   9.   1.   0.   0.]
 [  0.   0.  13.  15.  10.  15.   5.   0.]
 [  0.   3.  15.   2.   0.  11.   8.   0.]
 [  0.   4.  12.   0.   0.   8.   8.   0.]
 [  0.   5.   8.   0.   0.   9.   8.   0.]
 [  0.   4.  11.   0.   1.  12.   7.   0.]
 [  0.   2.  14.   5.  10.  12.   0.   0.]
 [  0.   0.   6.  13.  10.   0.   0.   0.]]


array([[  0.,   0.,   5.,  13.,   9.,   1.,   0.,   0.],
       [  0.,   0.,  13.,  15.,  10.,  15.,   5.,   0.],
       [  0.,   3.,  15.,   2.,   0.,  11.,   8.,   0.],
       [  0.,   4.,  12.,   0.,   0.,   8.,   8.,   0.],
       [  0.,   5.,   8.,   0.,   0.,   9.,   8.,   0.],
       [  0.,   4.,  11.,   0.,   1.,  12.,   7.,   0.],
       [  0.,   2.,  14.,   5.,  10.,  12.,   0.,   0.],
       [  0.,   0.,   6.,  13.,  10.,   0.,   0.,   0.]])

In [54]:
from sklearn import svm

In [55]:
clf = svm.SVC(gamma=0.001, C=100.0)

In [58]:
digits.target[:-1]

array([0, 1, 2, ..., 0, 8, 9])

In [61]:
clf.fit( digits.data[:-1], digits.target[:-1] )

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [63]:
digits.data[-1].reshape(-1,8)

array([[  0.,   0.,  10.,  14.,   8.,   1.,   0.,   0.],
       [  0.,   2.,  16.,  14.,   6.,   1.,   0.,   0.],
       [  0.,   0.,  15.,  15.,   8.,  15.,   0.,   0.],
       [  0.,   0.,   5.,  16.,  16.,  10.,   0.,   0.],
       [  0.,   0.,  12.,  15.,  15.,  12.,   0.,   0.],
       [  0.,   4.,  16.,   6.,   4.,  16.,   6.,   0.],
       [  0.,   8.,  16.,  10.,   8.,  16.,   8.,   0.],
       [  0.,   1.,   8.,  12.,  14.,  12.,   1.,   0.]])

In [65]:
digits.images[-1]

array([[  0.,   0.,  10.,  14.,   8.,   1.,   0.,   0.],
       [  0.,   2.,  16.,  14.,   6.,   1.,   0.,   0.],
       [  0.,   0.,  15.,  15.,   8.,  15.,   0.,   0.],
       [  0.,   0.,   5.,  16.,  16.,  10.,   0.,   0.],
       [  0.,   0.,  12.,  15.,  15.,  12.,   0.,   0.],
       [  0.,   4.,  16.,   6.,   4.,  16.,   6.,   0.],
       [  0.,   8.,  16.,  10.,   8.,  16.,   8.,   0.],
       [  0.,   1.,   8.,  12.,  14.,  12.,   1.,   0.]])

In [69]:
clf.predict(digits.data[-1:])

array([8])

In [82]:
help(pickle.dumps)

Help on built-in function dumps in module _pickle:

dumps(obj, protocol=None, *, fix_imports=True)
    Return the pickled representation of the object as a bytes object.
    
    The optional *protocol* argument tells the pickler to use the given
    protocol; supported protocols are 0, 1, 2, 3 and 4.  The default
    protocol is 3; a backward-incompatible protocol designed for Python 3.
    
    Specifying a negative protocol version selects the highest protocol
    version supported.  The higher the protocol used, the more recent the
    version of Python needed to read the pickle produced.
    
    If *fix_imports* is True and *protocol* is less than 3, pickle will
    try to map the new Python 3 names to the old module names used in
    Python 2, so that the pickle data stream is readable with Python 2.



In [ ]:
# pickle.dumps(clf)
# how to save it to disk？

In [97]:
# It is possible to save a model in the scikit by using Python’s built-in persistence model, namely pickle
import pickle
s=pickle.dumps(clf)
clf2=pickle.loads(s)
x, y = digits.data, digits.target

clf2.predict(x[0:19])


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
# in the specific case of the scikit, it more efficient on big data, but can onle pickle to the disk and not to a string.
from sklearn.externals import joblib
joblib.dump(clf, 'filename.pkl')

['filename.pkl']

In [84]:
joblib.load('filename.pkl')

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [100]:
import numpy as np
from sklearn  import random_projection

rng=np.random.RandomState(0)
print(rng)

In [105]:
x=rng.rand(10,2000)
print(x,'\n')
print(x.shape)

[[ 0.01109675  0.00176979  0.15505512 ...,  0.50189214  0.82852129
   0.18893591]
 [ 0.26996771  0.72437118  0.4810939  ...,  0.96721706  0.7182343
   0.56599457]
 [ 0.19574498  0.40305593  0.52577994 ...,  0.4520585   0.0225662
   0.72354188]
 ..., 
 [ 0.70723825  0.26233971  0.70349938 ...,  0.12260603  0.25590806
   0.58839217]
 [ 0.99101514  0.68349182  0.82538426 ...,  0.16285609  0.17744357
   0.08826577]
 [ 0.81925696  0.30741881  0.9851703  ...,  0.81013284  0.55103228
   0.22575586]] 

(10, 2000)


In [107]:
x=np.array(x,dtype='float32')
x.dtype

dtype('float32')

In [110]:
transformer=random_projection.GaussianRandomProjection()
print(transformer)

GaussianRandomProjection(eps=0.1, n_components='auto', random_state=None)


In [116]:
x_new=transformer.fit_transform(x)
print(x_new,'\n')
print(x_new.shape,'\n')
print(x_new.dtype)

[[ 0.7049005   0.40789627  0.03404759 ...,  0.87250525  0.19880978
  -0.21038957]
 [-0.11317274  0.35201298  0.18650254 ...,  0.43988852  0.59239997
  -0.64868838]
 [-0.21608947  0.28640286 -0.10852535 ..., -0.18806411 -0.06259976
  -0.43167459]
 ..., 
 [ 0.16007812  0.72986766 -0.68464572 ..., -0.06518336  0.09538063
  -0.30398444]
 [-0.14349004  0.13586519 -0.0470415  ..., -0.36686621  0.69053445
  -0.488642  ]
 [-0.63649443  0.52410945  0.22751337 ...,  0.18968822  0.56761367
  -0.38536751]] 

(10, 1973) 

float64


In [119]:
from sklearn import datasets
from sklearn import svm
iris=datasets.load_iris()
clf=svm.SVC()
clf.fit(iris.data,iris.target)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [122]:
list(clf.predict(iris.data[:3]))

[0, 0, 0]

In [131]:
print(clf,'\n')
print(clf.fit(iris.data,iris.target_names[iris.target]))
list(clf.predict(iris.data[:3]))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)


['setosa', 'setosa', 'setosa']

In [136]:
print(iris.target_names,'\n')
print(iris.target)
iris.target_names[iris.target]

['setosa' 'versicolor' 'virginica'] 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [153]:
import numpy as np
from sklearn import svm

rng=np.random.RandomState(0)
print(rng)
x=rng.rand(100,10)
print(x[0:3])
print(x.shape)
print('\n')

y=rng.binomial(1,0.5,100)
print(y)
print('\n')

x_test=rng.rand(5,10)
print(x_test)
print(x_test.shape)
print(x_test.dtype)

[[ 0.5488135   0.71518937  0.60276338  0.54488318  0.4236548   0.64589411
   0.43758721  0.891773    0.96366276  0.38344152]
 [ 0.79172504  0.52889492  0.56804456  0.92559664  0.07103606  0.0871293
   0.0202184   0.83261985  0.77815675  0.87001215]
 [ 0.97861834  0.79915856  0.46147936  0.78052918  0.11827443  0.63992102
   0.14335329  0.94466892  0.52184832  0.41466194]]
(100, 10)


[1 0 0 1 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0
 0 0 1 0 0 1 1 0 0 1 1 0 1 0 0 0 0 1 0 0 1 1 1 1 0 0 0 1 0 0 1 1 0 0 1 0 0
 1 0 0 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 1 1 0 1 0 1 1 1]


[[ 0.29594983  0.92929167  0.26590563  0.82814661  0.98510868  0.78339665
   0.51898992  0.06607426  0.47241379  0.43825595]
 [ 0.20279604  0.42358764  0.35775788  0.16368426  0.44137414  0.26279996
   0.52206242  0.03516006  0.90623142  0.81636431]
 [ 0.55258133  0.85180858  0.96239507  0.11052229  0.63083181  0.997994
   0.98788917  0.60332299  0.12802087  0.58319283]
 [ 0.00206464  0.19891133  0.95612

In [156]:
clf=svm.SVC()
print(clf)
clf.set_params(kernel='linear').fit(x,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [159]:
print(y)
print(clf.predict(x))
print(y-clf.predict(x))
print('\n')
print(clf.predict(x_test))

[1 0 0 1 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0
 0 0 1 0 0 1 1 0 0 1 1 0 1 0 0 0 0 1 0 0 1 1 1 1 0 0 0 1 0 0 1 1 0 0 1 0 0
 1 0 0 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 1 1 0 1 0 1 1 1]
[0 0 0 0 0 1 1 1 0 1 1 1 0 0 0 1 0 1 1 1 1 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 1
 1 1 1 1 0 1 1 0 1 1 1 0 1 1 0 1 1 1 0 0 0 0 0 1 0 1 0 1 0 0 1 1 0 0 1 0 1
 1 1 0 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 1 1]
[ 1  0  0  1  0  0  0 -1  0  0  0 -1  0  0  0 -1  0 -1  0  0 -1  1  1  1  0
  0 -1  0  0  0  0  0  0  1  1  0 -1 -1 -1  0 -1  0  0  0  0 -1  0  0  0  0
 -1  0 -1 -1  0  0  0  1  1  1  0  0 -1  0  0  0  0  0  0  0  0  0  0 -1  0
 -1  0  1  0  1 -1  1  0  0  0  1  0  1  0  0  0  0  0  1 -1  1 -1  0  0  0]


[1 0 1 1 0]


In [161]:
print(clf.set_params(kernel='rbf').fit(x,y))
print(y)
print(clf.predict(x))
print(y-clf.predict(x))
print('\n')
print(clf.predict(x_test))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
[1 0 0 1 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0
 0 0 1 0 0 1 1 0 0 1 1 0 1 0 0 0 0 1 0 0 1 1 1 1 0 0 0 1 0 0 1 1 0 0 1 0 0
 1 0 0 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 1 1 0 1 0 1 1 1]
[0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[ 1  0  0  1  0  0  0 -1  0  0  1  0  0  0  0  0  0  0  1  1  0  1  1  1  1
  0  0  0  0  0  0  0  1  1  1  0  0  0  0  1  0  0  1  1  0  0  1  1  0  0
  0  0  0  0  0  0  0  1  1  1  1  0 -1  0  0  0  0  1  1  0  0  1  0  0  1
  0  0  1  0  1  0  1  0  1  1  1  0  1  1  0  0  0  1  1  0  1  0  1  1  1]


[0 0 0 1 0]


In [175]:
from sklearn import svm
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer

x=[[1,2],[2,4],[4,5],[3,2],[3,1]]
print(x)
y=[0,0,1,1,2]
print(y.__len__)
print(y.__len__())
print('\n')
classif=OneVsRestClassifier(estimator=svm.SVC(random_state=0))
print(classif)
classif.fit(x,y).predict(x)

[[1, 2], [2, 4], [4, 5], [3, 2], [3, 1]]
<method-wrapper '__len__' of list object at 0x0000017C55688EC8>
5


OneVsRestClassifier(estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False),
          n_jobs=1)


array([0, 0, 1, 1, 2])

In [176]:
y=LabelBinarizer().fit_transform(y)
print(y)

[[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]]


In [177]:
classif.fit(x,y).predict(x)

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [180]:
from sklearn.preprocessing import MultiLabelBinarizer
y=[[0,1],[0,2],[1,3],[0,2,3],[2,4]]
print(y)
y=MultiLabelBinarizer().fit_transform(y)
print(y)
classif.fit(x,y).predict(x)

[[0, 1], [0, 2], [1, 3], [0, 2, 3], [2, 4]]
[[1 1 0 0 0]
 [1 0 1 0 0]
 [0 1 0 1 0]
 [1 0 1 1 0]
 [0 0 1 0 1]]


array([[1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0]])